name: Train and Commit Model

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'   # Retrain every Sunday at midnight UTC

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python scripts/train.py

      - name: Commit and push model
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add models/model.pkl
          git commit -m "Automated model retraining" || echo "No changes to commit"
          git push